### ISSUE TITLE
Running ms_rewards.py

### ISSUE THREAD

**Issue by siddrajpoot** [xMNG/Microsoft-Rewards-Bot#1]
Error when running script for the first time.

System: iMac v. 10.14

```
iMac:Microsoft-Rewards-Bot comp$ python ms_rewards.py
  File "ms_rewards.py", line 226
    logging.info(msg=f'Logging in {email_address}...')
                                                    ^
SyntaxError: invalid syntax
```

**Comment by xMNG** [comment]
Hi there, thanks for checking out my project. May I ask what version of python you are running? I think it may be an issue with f-strings (requires python 3.6+). I will be adding a requirements.txt and updating the readme shortly.

**Comment by siddrajpoot** [comment]
Thank you! The stock python installed on osx is 2.7 but I did install 3.7. I am not too familiar with python so is there a specific command I have to use for it to use 3.7?

**Comment by xMNG** [comment]
I am on linux but what I do to select the proper python version is to go to the terminal, and call the python executable by the path. For example: my python file is in /usr/bin/ and the executable is called python3.6. So the command I enter into the terminal `/usr/bin/python3.6 ms_rewards.py`.

Make sure you cd to the where the ms_rewards.py is located. Let me know if this helps.

**Comment by xMNG** [comment]
I pushed an update to the repo that replaced the code that caused the deprecation warning. Strangely enough that didn't appear on my side.

The change i did was:
`firefox_browser_obj = webdriver.Firefox(firefox_options=options, firefox_profile=profile)`
to
`firefox_browser_obj = webdriver.Firefox(options=options, firefox_profile=profile)`

Please let me know if that helps.

**Comment by siddrajpoot** [comment]
Hey!

So after some playing around with python and figuring everything out, I got it to work.

The steps I had to do for OS X:
1. Install python 3+
2. Run `python3 ms_rewards.py` file using instead of `python ms_rewards.py`
3. Installed the `required` and `selenium` modules using `pip3 install *moduleName*`
4. Install the geckodriver that selenium uses by running `brew install geckodriver`

After everything I got it to work! I dont have any information on python so maybe this is basic knowledge but this worked for me on OSX.

**Comment by xMNG** [comment]
Awesome. Were you able to max out the points from mobile/pc/edge and quizzes? 

If it's ok with you, I'm going to borrow some of your steps for OS X and incorporate it into the readme.

**Comment by xMNG** [comment]
Let me know how it goes!

I'm working on a few optimizations and improvements, hope to push them out soon. One thing i noticed was that microsoft sometimes does not pick up mobile searches. Attempting to debug whether it's the user agent or something else. I'll push a workaround in a little bit.

**Comment by siddrajpoot** [comment]
Yeah, it worked on all of my accounts! I've been looking for a solid Bing/Microsoft rewards bot for a while now that does all of the things yours does! One thing I was thinking about is making the accounts run in a random order every time. I wouldn't be surprised if Microsoft can detect the bot based on the same account rotation.

**Comment by xMNG** [comment]
Hey I updated the script with a randomized account order, plus many more updates. Take a look!
