### ISSUE TITLE
Not an Issue but a Heads Up

### ISSUE THREAD

**Issue by gjchester** [xMNG/Microsoft-Rewards-Bot#103]
Firefox had an upgrade a few days ago (Aug 2018),  Selenium tends to support 4 or 5 versions in each release.   

I'm not sure but I think the setup by the requirements will put in versions of the underlying drivers that will not work with the latest Firefox.  Firefox has an internal updater so you need to go into the About Preferences in Firefox and disable automatic upgrades to stop if breaking on you.

If you have had this running a while you may find you need to get the Chrome Driver / Selenium upgraded to get it working again.    I'm not quite seeing who I can do this yet...

**Comment by gjchester** [comment]
Got my Chrome Driver updated but now I see an error flash by in Fire fox that I'm using an unsupported flag (may be - Ignore certificate errors) that then closes the session.  

Anyone able to help, either to fix the issue or get me back to a lower version of Firefox  :) although to be honest anyone trying to use this now may see the same errors as they'll be on the newer firefox version
I'm not sure if the best solution is to work out if the code is fixable or fix Firefox to take the "wrong" certificates.


INFO :: root :: -------------------------PC-------------------------
2019-08-12 20:06:53,910 :: INFO :: root :: Logging in xxxxxxxxxxxxxx@outlook.com...
2019-08-12 20:06:54,076 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "ms_rewards.py", line 913, in <module>
    log_in(email, password)
  File "ms_rewards.py", line 265, in log_in
    browser.get('https://login.live.com/')
  File "/home/packt-download/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/home/packt-download/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/packt-download/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"F5F04A711176C15EA78E22AD4397CBBD","isDefault":true,"type":"default"},"id":1,"name":"","origin":"://"}
  (Session info: chrome=76.0.3809.87)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.15.0-55-generic x86_64)

**Comment by h4x0rm1k3** [comment]
Here's a link to ALL old versions of Firefox up to 31/7/19 I believe (v69.09b) https://ftp.mozilla.org/pub/firefox/releases/

Not sure what your issue is exactly as I use Chrome but hope the links help at least!

**Comment by gjchester** [comment]
Tried uninstalling Firefox and installing Chrome this morning but I get the same error appear quickly (unsupported flag - Ingore-Certificate-Errors).  It starts Chrome, and chrome appears maybe 4 or 5 times, (sometimes I see the browser window as such appear, sometimes I just see the icon in the task bar) but does not do any collection of points

I have this on a Virtual machine, and its possible chrome-driver/Selenium is trying to use Firefox but the change to chrome has broke some setting or link.   so I'll build another fresh VM shortly and try it again.

I suspect this is similar to issue #104, and the answer is to stop the web browser updating automatically (bad security but on a VM that only does this not a big risk) , or update the code to update the selenium / chrome driver as the web browser version increases.

**Comment by h4x0rm1k3** [comment]
I can't say i've noticed chrome opening when running the bot but then again chrome is usually open anyway so I might not notice that and I don't believe i've seen a flag error before in either the bot window or logs. I can only say that it does work for me but I did have to delete chromedriver 2 nights ago so that it would download the latest version as CMD would auto close within a minute and nothing ran as such and that sorted that issue out. Have you tried running the bot without a VM at all to see if that may be causing an issue? Might be worth a try to see if it starts working now. I can say that it doesn't take 20-30 mins per account now to run and is taking around 10 mins with the latest chromedriver now instead and I don't notice any issues running it at the same time as i'm browsing, gaming etc.

**Comment by gjchester** [comment]
Its run fine for about 6 months on a VM , and I have a few VM's permanently on so putting it on a VM is my preferred choice as it does matter if my main PC is on or off.

I think mine fell over a few days ago too, but I'll update later once I have a new VM running,.

**Comment by j027** [comment]
Until this issue gets fixed I’ll make my thing that runs the bot to delete the folder that has chromedriver in it so the latest chromedriver is downloaded every time.

**Comment by h4x0rm1k3** [comment]
Would you mind sending me a link or how to of how you do that please as I
wouldn't mind implementing that myself if possible. I did have an issue
last night where it ran 5 of my accounts but the last 1 had a weird error
regarding chromedriver so I stopped the bot, deleted chromedriver and just
ran the bot against the last account and it ran fine even though it was the
same version as I had already so it might be handy to delete that file
after it's ran to see if it stops that issue if it arises again tonight.

**Comment by j027** [comment]
@h4x0rm1k3 
I made a bat script to run the bot and update it with git, this is what it looks like with the thing added to delete chromedriver folder.
```
@echo off
:start
echo starting bot...
cd %userprofile%\Microsoft-Rewards-Bot
rmdir /q /s drivers
git pull
python ms_rewards.py --headless --mobile --pc --quiz
if %errorlevel% neq 0 goto start
```
the line that deletes the chromedriver folder is this one:
`rmdir /q /s drivers`

**Comment by gjchester** [comment]
Created a fresh VM, Re-installed everything and its working fine, I can only assume some update broke some underlying service or helper program or changed configs of one of the services/helper programs.
Can't troubleshoot much as it could be a combination of services playing up that others may not be using,, and the fix was a rebuild so closing issue.
