### ISSUE TITLE
Raspbian OSError: [Errno 8] Exec format error: 'drivers/chromedriver'

### ISSUE THREAD

**Issue by TK7K** [xMNG/Microsoft-Rewards-Bot#108]
Im having a difficult time getting this script to run on Raspbian. i have installed the requirements without issue and I have Chromium and Chrome Driver version 74.0.3729.157. from my research it seems to be an issue with chrome driver, but i've run out of ideas to check into.

Console:
`$ sudo python3.7 ms_rewards.py  --headless --mobile --pc --quiz`

Traceback (most recent call last):
  File "ms_rewards.py", line 898, in <module>
    browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
  File "ms_rewards.py", line 264, in browser_setup
    chrome_obj = webdriver.Chrome(path, chrome_options=options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'drivers/chromedriver'

-----------------

The log only looks like this:
2019-08-18 17:19:24,888 :: INFO :: root :: --------------------------------------------------
2019-08-18 17:19:24,888 :: INFO :: root :: -----------------------New------------------------
2019-08-18 17:19:24,888 :: INFO :: root :: --------------------------------------------------
2019-08-18 17:19:24,889 :: INFO :: root :: logins retrieved.
2019-08-18 17:19:41,023 :: INFO :: root :: # of search items: 129

2019-08-18 17:19:41,024 :: INFO :: root :: -------------------------MOBILE-------------------------

**Comment by LjMario007** [comment]
I'm having the same problem on Raspbian as well.
If you `apt install chromium-chromedriver` you still get the same error when you try to run the script.

**Comment by TK7K** [comment]
Yeah, i'm thinking that the chrome drivers are not working on Raspbian. I am in process of switching my Pi 4B to Unbuntu to see if that helps. There is no offical RPI4 Ubuntu release, but I will be trying the unofficial one at https://jamesachambers.com/raspberry-pi-ubuntu-server-18-04-2-installation-guide/
Im just waiting on my micro hdmi converter, since it doesn't support SSH right away and i don't have a screen for it. I will update once i have tried that.

Question to anyone else out there with Pi's - Have you been successful in getting this working? if so what OS are you running?

**Comment by LjMario007** [comment]
Funny, someone else reportedly got it working in an older issue -
https://github.com/xMNG/Microsoft-Rewards-Bot/issues/45#issuecomment-486032383

**Comment by TK7K** [comment]
I had taken a look at that post earlier and tried the steps. I thought it was really promising. Although, one of the steps was a bit misleading since the length of code had changed in our newer versions and Path was not on line 232 and there were several references to it. -
    "Next I head over to line 232 in ms_rewards.py, and modify replace the word “path” with 
    “/usr/lib/chromium-browser/chromedriver”"

Even with that, I did change several of the Path references one at a time and test, but no luck. If Ubuntu doesn't work for me, I might come back and give this another shot with a fresh build.

**Comment by LjMario007** [comment]
Wait a minute-
When you `apt install chromedriver` and do `whereis chromedriver` you get this:
```pi@raspberrypi:~ $ whereis chromedriver
chromedriver: /usr/bin/chromedriver```
I'm going to try what you said about replacing PATH with the chromedriver path but instead I'll try /usr/bin/chromed river

**Comment by TK7K** [comment]
Nice idea. Let me know if that works.

**Comment by LjMario007** [comment]
I replaced `path = os.path.join('drivers', 'chromedriver')` on line 241 with `path = "/usr/bin/chromedriver " `, and it worked!

**Comment by TK7K** [comment]
Awesome man! I got mine to work as well on Ubuntu using your edit above. Thanks!
