### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by piaomiaoguhong10** [xMNG/Microsoft-Rewards-Bot#11]
Dear xMNG,

I encountered the below error, but don't know how to deal with it.

File "ms_rewards.py", line 141
    chrome_obj = webdriver.Chrome(executable_path=r'/bin/chromedriver', chrome_options=options)
    ^
IndentationError: unexpected indent

With chromedriver version 2.46, chrome version v73 on a Centos 7 VPS.

**Comment by ShoGinn** [comment]
@piaomiaoguhong10 sounds like you uncommented the Linux code and didn't remove the spacing.

line up the chrome_obj with the one above.

Turn:
```
def browser_setup(headless_mode, user_agent):
    """
    Inits the chrome browser with headless setting and user agent
    :param headless_mode: Boolean
    :param user_agent: String
    :return: webdriver obj
    """
    options = Options()
    if headless_mode:
        options.add_argument('--headless')

    options.add_argument(f'user-agent={user_agent}')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')

    "Windows, MacOS"
    chrome_obj = webdriver.Chrome(chrome_options=options)

    "Linux"
    # chrome_obj = webdriver.Chrome(executable_path=r'/usr/local/bin/chromedriver', chrome_options=options)

    return chrome_obj
```

Into
```
def browser_setup(headless_mode, user_agent):
    """
    Inits the chrome browser with headless setting and user agent
    :param headless_mode: Boolean
    :param user_agent: String
    :return: webdriver obj
    """
    options = Options()
    if headless_mode:
        options.add_argument('--headless')

    options.add_argument(f'user-agent={user_agent}')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')

    "Windows, MacOS"
    # chrome_obj = webdriver.Chrome(chrome_options=options)

    "Linux"
    chrome_obj = webdriver.Chrome(executable_path=r'/usr/local/bin/chromedriver', chrome_options=options)

    return chrome_obj
```

**Comment by piaomiaoguhong10** [comment]
> @piaomiaoguhong10 sounds like you uncommented the Linux code and didn't remove the spacing.
> 
> line up the chrome_obj with the one above.
> 
> Turn:
> 
> ```
> def browser_setup(headless_mode, user_agent):
>     """
>     Inits the chrome browser with headless setting and user agent
>     :param headless_mode: Boolean
>     :param user_agent: String
>     :return: webdriver obj
>     """
>     options = Options()
>     if headless_mode:
>         options.add_argument('--headless')
> 
>     options.add_argument(f'user-agent={user_agent}')
>     options.add_argument('--no-sandbox')
>     options.add_argument('--disable-dev-shm-usage')
> 
>     "Windows, MacOS"
>     chrome_obj = webdriver.Chrome(chrome_options=options)
> 
>     "Linux"
>     # chrome_obj = webdriver.Chrome(executable_path=r'/usr/local/bin/chromedriver', chrome_options=options)
> 
>     return chrome_obj
> ```
> Into
> 
> ```
> def browser_setup(headless_mode, user_agent):
>     """
>     Inits the chrome browser with headless setting and user agent
>     :param headless_mode: Boolean
>     :param user_agent: String
>     :return: webdriver obj
>     """
>     options = Options()
>     if headless_mode:
>         options.add_argument('--headless')
> 
>     options.add_argument(f'user-agent={user_agent}')
>     options.add_argument('--no-sandbox')
>     options.add_argument('--disable-dev-shm-usage')
> 
>     "Windows, MacOS"
>     # chrome_obj = webdriver.Chrome(chrome_options=options)
> 
>     "Linux"
>     chrome_obj = webdriver.Chrome(executable_path=r'/usr/local/bin/chromedriver', chrome_options=options)
> 
>     return chrome_obj
> ```

awesome guy, thank you!

**Comment by xMNG** [comment]
Thank you @ShoGinn
