### ISSUE TITLE
Can this be run on the Linux operating system?

### ISSUE THREAD

**Issue by 15800834063** [xMNG/Microsoft-Rewards-Bot#16]
Can this be run on the Linux operating system? If you are running on a Linux operating system, do you need to install chrom?

**Comment by xMNG** [comment]
Yes I have it running on a ubuntu instance. Yes chrome is required, but the chromedriver will automatically be installed thanks to @ShoGinn

**Comment by 15800834063** [comment]
I mean, can I use it without using a graphical interface? Just the command line interface...

**Comment by xMNG** [comment]
Yes it can run in headless mode, via the --headless flag. Please see the readme.
