### ISSUE TITLE
Think the quiz function stopped

### ISSUE THREAD

**Issue by Firebreaker7** [xMNG/Microsoft-Rewards-Bot#19]
Still able to log in, but no longer working on new quizzes

**Comment by xMNG** [comment]
yeah the website bugged out. The PC searches are not tracked by MS by still awarded. I'm going to wait a few days and see if this issue resolves itself (it did in the past at the start of the month). If not, i'll push a fix.

**Comment by Firebreaker7** [comment]
Sounds like a plan. Thanks for the work on this!

**Comment by ShoGinn** [comment]
@xMNG the reason its not intractable is because of how it reads the ng-transclude.. referencing an actual link provides consistent results.

```
offer_links = [
                parent.find_element_by_xpath(
                    'div[contains(@class,"actionLink")]//descendant::a'
                ) for parent in parent_elements
            ]
```
instead of:
```
        offer_links = [parent.find_element_by_xpath('descendant::ng-transclude') for parent in parent_elements]
```

**Comment by xMNG** [comment]
@ShoGinn That works! I was looking at the (angular ?) element and noticed it was not displayed. Was playing around with the driver.execute_script() to make the element visible, but your solution is way more succinct and pythonic. I wonder why the link is clickable but not the ng-transclude which was working before. Then again I have no idea what it is yet, i just started learning front end.   

One question, I used js in the console and tested some xpaths via $x. Do you know why the $x('div[contains(@class,"actionLink")]//descendant::a') doesn't return any results when searching for the links?

**Comment by xMNG** [comment]
Pushed the fixes, I only tested it working on my local machine. Please let me know if there are any further errors on this issue.

**Comment by ShoGinn** [comment]
It should if you use chrome ;)


Sent from Yahoo Mail for iPhone


On Saturday, March 2, 2019, 11:33 AM, xMNG <notifications@github.com> wrote:


@ShoGinn That works! I was looking at the (angular ?) element and noticed it was not displayed. Was playing around with the driver.execute_script() to make the element visible, but your solution is way more succinct and pythonic. I wonder why the link is clickable but not the ng-transclude which was working before. Then again I have no idea what it is yet, i just started learning front end.

One question, I used js in the console and tested some xpaths via $x. Do you know why the $x('div[contains(@Class,"actionLink")]//descendant::a') doesn't return any results when searching for the links?

**Comment by ShoGinn** [comment]
*edited for better clarity*
I see what you are saying, that when using javascript to try and pull the xpath you can't even get any results.

You have to add the prefix of `//` to  `div[contains(@class,"actionLink")]//descendant::a`

so `$x('//div[contains(@class,"actionLink")]//descendant::a')` gives you results

**Comment by xMNG** [comment]
ah ok that makes sense. I'll do more reading up on this.

Thanks again ShoGinn

**Comment by ShoGinn** [comment]
I was going to change your other xpath but im also pretty newb in regards to multiple parents up ;)

the ..\..\..\ one

**Comment by xMNG** [comment]
closed thanks to @ShoGinn
