### ISSUE TITLE
Awesome - But some issues.

### ISSUE THREAD

**Issue by ShoGinn** [xMNG/Microsoft-Rewards-Bot#2]
I love seeing the ingenuity of selenium bots. I have been piecing together a bot privately just because my coding is not nearly as refined as yours!

Thanks for commenting on each function!

I had to modify yours to work in my instance. I use the selenium grid and docker to do the same thing as yours and it provides a nice clean approach.

Here is the browser code I use:

```
def browser_setup(headless_mode, user_agent):
    options = webdriver.ChromeOptions()
    options.add_argument("--disable-extensions")
    options.add_argument("--window-size=1280,1024")
    options.add_argument("--log-level=3")
    options.add_experimental_option("prefs", {
        "profile.default_content_setting_values.geolocation": 1})  # geolocation permission, 0=Ask, 1=Allow, 2=Deny
    options.add_argument("--headless")
    options.add_argument("user-agent=" + user_agent)
    options.add_argument('--disable-infobars')
    options.add_argument('--incognito')
    caps = options.to_capabilities()
    driver = webdriver.Remote(command_executor='http://selenium-grid:4444/wd/hub', desired_capabilities=caps)
    return driver
```

If of course has to switch to chrome because I couldn't get your profile to work in the WebDriver.Remote (if you are smarter on that I would appreciate it!)

---
I have a question on why you always do 50 search terms?

Why not do your get point total at the beginning and then take lets say 0/300 and then 300/5 = 60.

Also I use the Points Breakdown to get that info as it seems to be easier.

With double points this month you need 60 searches ;)

Or if someone runs the script more than once you can limit it to that amount.

---
Speaking of searches, I understand using the newsapi.org is a good for developers.
Google has a free one without api ;)

`https://trends.google.com/trends/api/dailytrends?hl=en-US&ed={}&geo=US&ns=15`
```
  def __update_search_queries(self, timestamp, last_request_time):
        if last_request_time:
            time.sleep(max(0, 20 - (
                    datetime.now() - last_request_time).total_seconds()))  # sleep at least 20 seconds to avoid over requesting server
        response = urlopen(self.__TRENDS_URL.format(timestamp.strftime("%Y%m%d")),
                           context=ssl.SSLContext(ssl.PROTOCOL_TLSv1))
        last_request_time = datetime.now()
        response = json.loads(response.read()[5:])

        # self.__queries = [] # will already be empty
        for topic in response["default"]["trendingSearchesDays"][0]["trendingSearches"]:
            self.__queries.append(topic["title"]["query"].lower())
            for related_topic in topic["relatedQueries"]:
                self.__queries.append(related_topic["query"].lower())
        return last_request_time
```
poach that if you want ;) just requires ssl import.

---
This might be a by-product of using chrome and not Firefox, but this error:

```
date-time :: ERROR :: Sign in splash not detected.
Traceback (most recent call last):
  File "ms_rewards.py", line 123, in wait_until_clickable
    WebDriverWait(browser, time_to_wait).until(ec.element_to_be_clickable((by_, selector)))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```
I know you usually catch all exceptions but not in this case ;)

I have not found a situation that after searching and not closing browser windows that you need to look for the sign-in page??

---
The next issue is that you never quit the driver only the browser.

I recommend adding:
```
driver.quit()
```
at the end of your ___main___ as it disposes of all the browsers.

---

This is awesome code with some of the cleanest implementations of logging!

**Comment by xMNG** [comment]
Hey, big thanks for reviewing my code!!

> browse code
Thanks, I'll take a look and likely use your browser code. I'd definitely take a look at selenium grid and docker. Any resources you found that helped you get started? 
Not sure on why firefox is not working. Did you install geckodriver on your docker instance?

> 50 questions
I left it at a constant 50 because when I was initially testing the bot, I found that some searches were not being registered. I think I fixed the problem and will update this with my next push. Unfortunately I was unable to complete the wild kingdom so I don't get double points. :[

> google trends
I'll definitely use this, nice find!! 

> sign-in page
In my current iteration, I'm finding that ~half the time the bot hangs after the login and goes to the sign-in splash. I'll have to do some more testing to see what is happening. I did have the sign-in splash captured in the local version of the code. Will be pushing the update soon.

>browser.quit()
I named my driver browser instead. I'm not sure if this is a good practice. Now that I think about it, keeping it 'driver' probably makes more sense. 

Also, I'm trying to make my code more OOP, but not really sure how to proceed or if it even makes sense. What are your thoughts on this? Again thanks for checking my project out!

**Comment by ShoGinn** [comment]
The browser thing is just different when using the remote call.

I found an example of the differences in some other code:

```
    def test_firefox(self):
        expected_webdriver = mock()
        profile = mock()
        when(webdriver).FirefoxProfile().thenReturn(profile)
        caps = webdriver.DesiredCapabilities.FIREFOX
        if SELENIUM_VERSION.major >= 3 and SELENIUM_VERSION.minor >= 8:
            log_file = self.get_geckodriver_log()
            when(webdriver).Firefox(capabilities=caps,
                                    options=None,
                                    firefox_profile=profile,
                                    log_path=log_file).thenReturn(expected_webdriver)
        else:
            when(webdriver).Firefox(capabilities=caps,
                                    firefox_profile=profile).thenReturn(expected_webdriver)
        driver = self.creator.create_firefox({}, None, None)
        self.assertEqual(driver, expected_webdriver)
        verify(webdriver).FirefoxProfile()

    def test_firefox_remote(self):
        url = 'http://localhost:4444/wd/hub'
        profile = mock()
        when(webdriver).FirefoxProfile().thenReturn(profile)
        expected_webdriver = mock()
        caps = webdriver.DesiredCapabilities.FIREFOX
        when(webdriver).Remote(command_executor=url,
                               desired_capabilities=caps,
                               browser_profile=profile).thenReturn(expected_webdriver)
        driver = self.creator.create_firefox({}, url, None)
        self.assertEqual(driver, expected_webdriver)
```
The points check has fixed a lot of the issues when it comes to unregistered searches, It checks at the beginning of searches then at the end and continues with more if necessary.

But if you repeat the same searches with the same exact search term it sometimes doesn't register. 

So keeping a log of what has been searched and not using it, is the solution for me.

The browser.quit() is just a better practice for selenium rather than close. Since quit closes the driver and the browser window instead of waiting not he gecko driver to timeout.

**Comment by ShoGinn** [comment]
I look forward to your next push so I can start contributing ;)

I would hate to fix the problems and add a pull request of fixes you already made.

**Comment by xMNG** [comment]
Hey I pushed an update with some big changes (new things I learned!). I still would like to do a check on search completion. My initial thoughts on this are to do a generator copy of the search terms for each call of the search() function, with checks every 20 or 30 searches (depending on whether pc vs mobile search mode). What do you think? Is there a better way?

**Comment by xMNG** [comment]
Thanks for the link, I'll go through it and borrow some ideas.

The argparse is great, you can actually complete everything if you enter all the commands! I left it optional for the flexibility.

I'm self taught. I did complete the book automate the boring stuff and took a certificate class. Doing projects was the best teacher though. Is python your first programming language or are you coming from another language?

**Comment by ShoGinn** [comment]
I was a C# programmer many years ago and then perl and mostly *nix scripting so python makes sense , but optimizing code and class programing still hasn't clicked.

**Comment by xMNG** [comment]
Thanks for the update. First time to everything, including accidentally pushing passwords. Won't happen again with this new technique!

I thought I managed to wipe the commit but I guess I'm still learning!

**Comment by ShoGinn** [comment]
so I've stolen some of your code to optimize the quizzes on the linked script.

One thing I noticed on your iter is that if a quiz is already started it will never find the "start quiz" which can be an issue, just wanted to point that out while I was thinking of it!

So just add a "script started check" and you should be fine!

**Comment by xMNG** [comment]
Great idea, I did encounter that issue when microsoft's website bugged out. It would show the same completed quiz or restarted quiz on the next page. I'll add a check on the next update. I have a few updates that I haven't pushed yet. 

Let me know if you think of anything else! Thanks.

**Comment by ShoGinn** [comment]
You give up ;)

**Comment by xMNG** [comment]
Hey there! Nope, I just pushed an update to fix the daily poll to accommodate changes on microsoft's end. Also added a sign-in checker which clicks through the sign in prompts after clicking on a quiz (even though the account is logged in). 

I find that running the script via cron on digital ocean at around 4am EST works to complete all searches and quizzes, since i think everything is reset around 3am EST. The script is working great, with 100+ day streak on my accounts. The only time a streak would fail so far is if the website's quiz is bugged (can generally tell because of the numerous posts on r/MicrosoftRewards. 

I've been studying, practicing, and learned a lot of new things in both python and selenium since the last major update. I have to find some time to implement them, likely as part of a rewrite. Is there any feature in particular you are looking for?

**Comment by ShoGinn** [comment]
I feel like your coding has been one way ;)

I took your TODO advice and changed over to requests.

Its super easy.

```
dates = self.get_dates()
        for date in dates:
            url = f'https://trends.google.com/trends/api/dailytrends?hl=en-US&ed={date}&geo=US&ns=15'
            response = requests.get(url)
            response = json.loads(response.text[5:])
            for topic in response["default"]["trendingSearchesDays"][0]["trendingSearches"]:
                self.__queries.append(topic["title"]["query"].lower())
                for related_topic in topic["relatedQueries"]:
                    self.__queries.append(related_topic["query"].lower())

        reduced_queries = set(self.__queries).difference(self.search_hist)
        self.__queries = list(reduced_queries)
        self.log.debug("# of search items: " + str(len(self.__queries)))
```

I like your code to get multiple days of searches...

I track my searches so as to not repeat.. not sure if it matters.

I noticed you were having problems in another issue, about getting search status.

I use the Chrome Extension webpage to get status (seems to be very consistent)

```
    __EXT_URL = "http://www.bing.com/rewardsapp/bepflyoutpage?style=chromeextension"

```

```
def __new_search_progress(self):
        """
        __search_progress elements are
        0 current web progress
        1 complete web progress
        2 current mobile progress
        3 complete mobile progress
        """
        if len(self.__driver.window_handles) == 1:  # open new tab
            self.__driver.execute_script("window.open('about:blank');")
        self.__latest_window()
        self.__driver.get(self.__EXT_URL)
        self.__wait_until_visible(By.XPATH, '//*[@id="flyoutContent"]', self.__WEB_DRIVER_WAIT_LONG)
        web_elements = self.__driver.find_element_by_class_name('pcsearch')
        mobile_elements = self.__driver.find_element_by_class_name('mobilesearch')
        # noinspection PyStatementEffect

        web_elements.location_once_scrolled_into_view  # Used for  mobile to scroll down
        if web_elements:
            self.__search_progress[0], self.__search_progress[1] = [int(i) for i in
                                                                    re.findall(r'(\d+)', web_elements.text)]
        else:
            self.__search_progress[0], self.__search_progress[1] = 0, -1
        if mobile_elements:
            self.__search_progress[2], self.__search_progress[3] = [int(i) for i in
                                                                    re.findall(r'(\d+)', mobile_elements.text)]
        else:
            self.__search_progress[2], self.__search_progress[3] = 0, -1

        self.__main_window()
        self.log.debug(f'Web Search Progress: {self.__search_progress[0]}/{self.__search_progress[1]}')
        self.log.debug(f'Mobile Search Progress: {self.__search_progress[2]}/{self.__search_progress[3]}')

        return self.__search_progress

```

thought I would share!

**Comment by xMNG** [comment]
Very nice. I may have to switch to chrome. How are you able to get selenium to load the extension?

**Comment by ShoGinn** [comment]
the extension just uses that webpage in __EXT_URL

So its not like Im using a chrome extension, just what the internals of the extension is using ;)

Since they changed the dashboard page it broke most of my code.

**Comment by xMNG** [comment]
Ah i see it now. This is awesome!! I was thinking about using this same drop-down on the bing.com page (after clicking on the ribbon icon). This will work even better. How did you find this?

**Comment by ShoGinn** [comment]
It is the ribbon icon ;)
And I just looked at the source for the chrome extension...
