### ISSUE TITLE
.

### ISSUE THREAD

**Issue by AlphaXDO** [xMNG/Microsoft-Rewards-Bot#22]
I got halfway I installed pip and then installed the requiremnets but when i type python ms_rewards.py --headless --mobile --pc --quiz it say it is not a recognized command on commmand prompt

**Comment by xMNG** [comment]
Sounds like your python may not be in PATH.

Type in `python` in the command line, does it produce the same error?

If you are on windows, you can follow these instructions to add python to PATH. [stackoverflow](https://superuser.com/questions/143119/how-do-i-add-python-to-the-windows-path

**Comment by pearlheartgtr** [comment]
I've found that running command prompt from the folder ms_rewards.py is in is helpful, too.

**Comment by AlphaXDO** [comment]
I been able to get it done it would also be better if you had a loading bar or points counter to tell you how how many points you are getting kind of like Microsoft Reward Automater. https://www.reddit.com/r/MicrosoftRewards/comments/8aa9u6/new_bot_microsoft_rewards_automator/

**Comment by ShoGinn** [comment]
@AlphaXDO That link is dead, so hard to pinpoint the objective.

**Comment by AlphaXDO** [comment]
I can send you applications files i think it even has the source code

**Comment by AlphaXDO** [comment]
@ShoGinn I can send you applications files i think it even has the source code

**Comment by AlphaXDO** [comment]
I tried it everything looked like it worked until I saw points and nothing changed. Can you guys make a youtube tutorial or something.

**Comment by ShoGinn** [comment]
@AlphaXDO if you want to publish the code here on Github and link it that would be a start!

As for your request to do a tutorial?? This is pretty basic python code that does require some background knowledge in running python. 

The README does a pretty good job of outlining how to run the script, if you are having python install issues (using windows etc) look up some youtube on how to install python.

**Comment by AlphaXDO** [comment]
Do you have a discord? I will send it to you there.

**Comment by ShoGinn** [comment]
@AlphaXDO Look me up -- Same Name

**Comment by AlphaXDO** [comment]
I need the 4 digits after your username

**Comment by ShoGinn** [comment]
@AlphaXDO   Yeah, I edited the post and added them ;)
