### ISSUE TITLE
New Quiz Type

### ISSUE THREAD

**Issue by ShoGinn** [xMNG/Microsoft-Rewards-Bot#28]
Looks like MS is rolling out a new method in their Lightning Quizzes

I have create a semi-hack way of doing it, but don't want to publish the results until we start seeing more issues.

What is happening is that the quiz starts with 
```
rqAnswerOption0
```
But once you get into the quiz, the class it looks for `rqOption` is not available.

If you change it up and modify the code to just use the `rqAnswerOption` there are multiple javascript entries which prevent the native mode clicking.

Also there are more than the normal 4 options (8 this last time)

Forcing synthetic is not a good option, so I never even went down that path.

Let me know what you all think!

**Comment by xMNG** [comment]
I noticed some other issues with quizzes, including clicking the quiz links and closing the quiz splashes. 

What are javascript entries and forcing synthetic?

**Comment by ShoGinn** [comment]
The javascript I saw was using double entries with shadowed elements. So using native browser elements and trying to click references the wrong element. There is a JavaScript that checks for mouse clicks. That’s my best guess from my delving in today.

**Comment by blakekl** [comment]
At a minimum, the script should be fault tolerant and finish running when encountering an unknown circumstance like this.

**Comment by ShoGinn** [comment]
You are correct, this is why we changed it to look for the the element before clicking.
