### ISSUE TITLE
Can't find class name with name pcsearch

### ISSUE THREAD

**Issue by Bentechy66** [xMNG/Microsoft-Rewards-Bot#32]
Here is the traceback: `Traceback (most recent call last):
  File "ms_rewards.py", line 806, in <module>
    search(search_list)
  File "ms_rewards.py", line 464, in search
    if get_point_total(pc=True):
  File "ms_rewards.py", line 667, in get_point_total
    pcsearch = browser.find_element_by_class_name('pcsearch')
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"pcsearch"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-135-generic x86_64)`

Running on Ubuntu Server with the options `--headless --mobile --pc --quiz`

**Comment by Bentechy66** [comment]
Running the program without the `--pc` flag appears to work as intended (but obviously without the points for the PC search)

**Comment by Bentechy66** [comment]
Furthermore, it appears that even if one omits the `--pc` flag, the various errors shown above still appear in the log file and one does not gain any points from searches.

**Comment by Bentechy66** [comment]
It appears that from running the script I did in fact yield 6 of the avaliable 30 points from Bing Search.

**Comment by Bentechy66** [comment]
It appears that each time one runs the script, one PC search is completed and then the program exits.

**Comment by ShoGinn** [comment]
log into your account and goto https://www.bing.com/rewardsapp/bepflyoutpage?style=chromeextension

Also are you level 1 or level 2?

You should see:

![image](https://user-images.githubusercontent.com/2660603/55185155-fcade880-5150-11e9-86a0-47bfbba81b42.png)

If it doesn't look like that let us know ;)

**Comment by xMNG** [comment]
I think you are in the UK? Actually there is an open pull request that I haven't  had time to think over. See #21

**Comment by ShoGinn** [comment]
@xMNG it was edge searches that was the != NA stuff.. so might be related

**Comment by xMNG** [comment]
For now if you apply the fixes in jbasoo's branch #21  it will work in the UK. I have to think it over next week. I'd like the code to only check for non US when the -UK flag is enabled.

**Comment by Bentechy66** [comment]
@xMNG yes, I can confirm I am in the UK. I will pull down #21 and report back.

**Comment by ShoGinn** [comment]
I’ll put some brain bytes into this as well in regards to an automatic method ;)

**Comment by Bentechy66** [comment]
![image](https://user-images.githubusercontent.com/19192864/55185602-9b0b6f80-518c-11e9-9fe4-8b48fbd23c15.png)
The page looks like this

**Comment by ShoGinn** [comment]
Yeah it’s a level 1 issue not a UK issue

**Comment by xMNG** [comment]
Yeah I think we need a check for level 1 vs level 2. 
I think if line 667 `pcsearch = browser.find_element_by_class_name('pcsearch')` was wrapped in try/except to return false if the element is not found, this would fix the problem. 

@Bentechy66 Want to give it a shot?

**Comment by Bentechy66** [comment]
#21 Did not fix the issue. Trying @xMNG's suggestion now.

**Comment by Bentechy66** [comment]
@xMNG's suggestion did remove the message from the log, however it is now complaining about `credits2`. Also, possibly unrelated note, but the log now has rather a lot of this in it: 
`2019-03-28 19:19:04,634 :: WARNING :: urllib3.connectionpool :: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f639f0aff28>: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/redacted6614987860e67717redacted
`

**Comment by xMNG** [comment]
oh no...not credits2 again. That's giving me nightmares. The script should log the error but continue running. Is that the case for you?

The log is from chromedriver and can be safely ignored i think. Not sure if there is a way to suppress.

**Comment by Bentechy66** [comment]
`Traceback (most recent call last):
  File "ms_rewards.py", line 786, in <module>
    search(search_list, mobile_search=True)
  File "ms_rewards.py", line 456, in search
    if get_point_total(mobile=True):
  File "ms_rewards.py", line 662, in get_point_total
    pcsearch = browser.find_element_by_class_name('pcsearch')
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"pcsearch"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-135-generic x86_64)
`

**Comment by xMNG** [comment]
That's line 667 still. Have you tried wrapping in try/except NoSuchElementException? It should `return False` in the event of the exception. 

If you make the PR, i'll approve it.

**Comment by Bentechy66** [comment]
Just going to run script without the `--pc` flag for now.

**Comment by Bentechy66** [comment]
Even after wrapping 667 in a try/except statement, PC searches are still not being carried out when the `--pc` flag is specified

**Comment by Bentechy66** [comment]
Also it seems that when I manually search for certain topics on Bing (ie Castles) I get quizzes that the script has not automatically completed, and after these I get the option to do more supersonic quizzes - worth 30 points each?

**Comment by ShoGinn** [comment]
@Bentechy66 this is a known issue in other scripts due to being level 1 ;)

I would recommend just completing the month manually and then once you are upgraded to level 2... PROFIT

**Comment by Bentechy66** [comment]
The potential point loss from quizzes is a level 1 issue?

**Comment by ShoGinn** [comment]
Correct.. Level 1 labels things weird.. their Javascript is confusing indeed

**Comment by xMNG** [comment]
I wonder if we could check for level 1 and just do a "dumb" completion run. 

Also I am in school again for JS, hopefully I'll bring some more ideas on board in the near future. But for now, not enough time to do all the things I want to do!

**Comment by massivenights** [comment]
This isn't limited to Level 1 users, I think it's a UK thing. I'm UK and Level 2 and I'm getting a similar error.

`2019-04-02 09:41:42,586 :: INFO :: root :: Search Start
2019-04-02 09:41:49,145 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "ms_rewards.py", line 799, in <module>
    search(search_list)
  File "ms_rewards.py", line 460, in search
    if get_point_total(pc=True):
  File "ms_rewards.py", line 673, in get_point_total
    int, browser.find_element_by_class_name('edgesearch').text.split('/'))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 563, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"edgesearch"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.12.6 x86_64)`

**Comment by massivenights** [comment]
The Level 2 Rewards flyout looks like this in the UK for reference, it doesn't include the Edge :
![Screen Shot 2019-04-02 at 10 05 13](https://user-images.githubusercontent.com/46960839/55390369-fd6ac400-552e-11e9-996f-7c86d371ffe4.png)

Edge Search is included in the PC search count (daily it's 12 for Edge and 90 for PC)

**Comment by Bentechy66** [comment]
The above issue was fixed, however, now when I run the script it only partly completes the first 2 accounts in my list and then quits.

**Comment by xMNG** [comment]
Not sure why this is happening. Although I did have a mobile search not register recently. Will have to do some debugging.

**Comment by xMNG** [comment]
closed with update 2019.04.01, also see #35
