### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by tb0111** [xMNG/Microsoft-Rewards-Bot#37]
Getting this error on run. Installed requirements.txt using pip.

**Comment by xMNG** [comment]
Hi can you verify that requests is installed? Enter `python -m pip list` into your terminal to see the installed packages. Also do check if you have multiple versions of python installed on your system and check the appropriate one.

**Comment by tb0111** [comment]
Output:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package    Version 
---------- --------
certifi    2019.3.9
chardet    3.0.4   
idna       2.8     
pip        19.0.3  
requests   2.21.0  
selenium   3.14.0  
setuptools 40.9.0  
urllib3    1.24.1  
wheel      0.33.1

**Comment by tb0111** [comment]
I uninstalled Python 2.7 (So just 3.6 is remaining) and I now get this error 
root@DietPi:~/Microsoft-Rewards-Bot# python ms_rewards.py --headless --mobile --pc --quiz
  File "ms_rewards.py", line 98
    url = f'https://trends.google.com/trends/api/dailytrends?hl=en-US&ed={date}&geo=US&ns=15'
                                                                                            ^
SyntaxError: invalid syntax

**Comment by connect-dots** [comment]
Interestingly enough I also got the above error on Wednesday (3rd April)
`url = f'https://trends.google.com/trends/api/dailytrends?hl=en-US&ed={date}&geo=US&ns=15'
^
SyntaxError: invalid syntax`
System was Ubuntu 18.04, python 3.6, (UK if it helps).
Windows 10 machines however do not seem to have this issue??

**Comment by ShoGinn** [comment]
Run it with python3 and see if it does it 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xMNG** [comment]
ubuntu defaults to python 2.7 if you enter `python` in the terminal. Try entering `python3.6` instead. The errors with url is very likely due to f-strings not supported in 2.7.

**Comment by connect-dots** [comment]
Thanks for the advice will try it tonight.

**Comment by connect-dots** [comment]
The above 'python3' recommendation fixed it for me. Many thanks.
