### ISSUE TITLE
Issue when changing username and password

### ISSUE THREAD

**Issue by Tinycyclops** [xMNG/Microsoft-Rewards-Bot#39]
Hi! 
I'm really new to everything with cmd or python(just started some code.org in school) so i'm pretty sure i must be screwing something up somewhere, but I can't figure out what that is. 

on first setup, it works fine, when I then change to another account to break up the usage I get
this in traceback  "File "ms_rewards.py", line 821, in <module>
    login_dict = get_login_info()
  File "ms_rewards.py", line 162, in get_login_info
    return json.load(f)
  File "C:\Users\jeff\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\jeff\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\jeff\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\jeff\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 136 (char 135)

It works fine if then change back to the first account, and I get the same results if I try again in a virtual python enviroment. logs are basically blank. 
[ms_rewards.log](https://github.com/xMNG/Microsoft-Rewards-Bot/files/3056186/ms_rewards.log)

What am I missing?
thank you.

**Comment by xMNG** [comment]
Does your password have a \ character? If so, i'd recommend changing the password to one without it. See this error `json.decoder.JSONDecodeError: Invalid \escape: line 1 column 136 (char 135)`

**Comment by Tinycyclops** [comment]
And that was what I was missing. Thank you!
