### ISSUE TITLE
Bot does not complete 'Poll' tasks

### ISSUE THREAD

**Issue by tb0111** [xMNG/Microsoft-Rewards-Bot#40]
Seems like an easy one to implement, it doesn't matter which option is chosen.

Thanks!

**Comment by ShoGinn** [comment]
@tb0111 it sure does ;)

https://github.com/xMNG/Microsoft-Rewards-Bot/blob/91cf1113bc9eb5f9440ebb6d4b4d6bf99a634755/ms_rewards.py#L563

**Comment by xMNG** [comment]
I've had about one poll out of maybe 100 fail to complete, but havent been able to isolate the problem. If you can help me debug it, that'd be great. 

I think, time permitting in the future, i'd restructure the daily quiz completions to return to the dash and check again for any open offers. Or something else.
