### ISSUE TITLE
Account #3 does not get completed

### ISSUE THREAD

**Issue by tb0111** [xMNG/Microsoft-Rewards-Bot#42]
Acount number 3, a level 1 account, is not having it's tasks completed correctly. Why is this?

**Comment by tb0111** [comment]
The json file looks like this:
{"aaaaa@gmail.com": "*************", "bbbbb@live.com": "*********", "ccccccc@yahoo.co.uk": "********"}

Note that passwords contiain many special charecters (they are randomly generated passwords) so I'm thinking that this may be causing the error.

**Comment by gjchester** [comment]
Hi, 
Manually get the account to Level 2 (should take 2 days to do it form zero points) first.     My wifes Rewards  had this issue but once level 2 it worked fine.

Somewhere in the issues thread is a comment the Javascript code is slightly different for level 1 accounts, and given it only takes 10 minutes a day of  clicking for 2 days to get you to level 2, it's probably easier to do that than branch the code to make it cope with Level 1

**Comment by ShoGinn** [comment]
Other repositories in the past had specified that level 1 is not supported due to these exact problems. Mainly because developing for level requires creating new accounts by developers. I would second the recommendation of @gjchester 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
