### ISSUE TITLE
Can't get bot to work, need help please.

### ISSUE THREAD

**Issue by pyrokidd89** [xMNG/Microsoft-Rewards-Bot#49]
I am having an issue getting this to run. This is my first time using python so I am sure I am doing something wrong or am missing something. Attached is part of my log file you someone can take a look. 
[ms_rewards_Log.log](https://github.com/xMNG/Microsoft-Rewards-Bot/files/3144776/ms_rewards_Log.log)

**Comment by ShoGinn** [comment]
Make sure you are running the latest version of chrome.

**Comment by MacMarde** [comment]
Did you install Selenium?

**Comment by pyrokidd89** [comment]
...so it seems that chrome being outdated was my issue. Maybe there should be a more obvious error returned if chrome is not up to date?

**Comment by ShoGinn** [comment]
The error was obvious ;)

```
This version of ChromeDriver only supports Chrome version 74
```
