### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by lukedukeus** [xMNG/Microsoft-Rewards-Bot#5]
I get this error, but when I google it, It says my firefox and geckodriver are mismatched, but I have geckodriver 23 and firefox 64. I am on Xubuntu on a rasberry pi 3b.

`
2018-12-25 08:35:52,431 :: INFO :: root :: ***************PC***************
2018-12-25 08:35:54,321 :: ERROR :: root :: Failure at main()
Traceback (most recent call last):
  File "ms_rewards.py", line 741, in <module>
    browser = browser_setup(parser.headless_setting, PC_USER_AGENT)
  File "ms_rewards.py", line 147, in browser_setup
    firefox_browser_obj = webdriver.Firefox(options=options, firefox_profile=profile)
  File "/home/pi/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
`

**Comment by xMNG** [comment]
Hey which geckodriver did you download? ARM or linux?

**Comment by lukedukeus** [comment]
online forums say that this error is due to firefox being out of date, and newer versions of firefox dont work on pi. Would it work to use chromedriver instead of geckodriver, and if so, how would i do this

**Comment by ShoGinn** [comment]
@lukedukeus running selenium on arm seems to be the problem.

@xMNG not sure if my solution to run selenium remote with docker would create a solution since I don't run ARM as my selenium platform.

**Comment by lukedukeus** [comment]
ok, thanks.  also, @xMNG , if you want, I have a python script  that scrapes reddit posts for links, and parses them. Do you want it to add to your bot?

**Comment by xMNG** [comment]
@lukedukeus  Yes that'd be awesome. 

@ShoGinn thanks for your help as always.

happy holidays!

**Comment by lukedukeus** [comment]
So upon looking for it, I realised I didn't include it in my backup before switching systems. I wrote up a quick scetch, and its kind of rough, but works.

`import urllib2
import html2text
import re
from time import sleep
from bs4 import BeautifulSoup, SoupStrainer



#################################################################

url='https://www.reddit.com/r/MicrosoftRewards/.json'
page = urllib2.urlopen(url)
sleep(10)

html_content = page.read()
sleep(10)

rendered_content = html2text.html2text(html_content)
sleep(10)
	
file = open('file_text.txt', 'w')
file.write(rendered_content)
with open('file_text.txt','r') as f:
    for link in BeautifulSoup(f.read(), "lxml", parse_only=SoupStrainer('a')): 
        if link.has_attr('href'):
			f1=open('links.txt', 'w+')
			print(link['href'])
			f1.write(link['href'])
			
f1.close()




######################################################`


 There is a better way to do this. In the original version I used PRAW to grab the latest 50 posts, then used regex to filter out the links, then used selenium to login and visit the links one by one. 

Still dissapointed that I lost the original, but I hope this helps

**Comment by xMNG** [comment]
Very interesting. Since the data comes in a json, we can just use the json module and look for titles with "no tracking email links" and parse the text for the links.

One issue i noticed is that sometimes people post links **with** tracking. That could cause a ban if dozens of people use the same link.

**Comment by ShoGinn** [comment]
@xMNG using response should be easy to do this, but you are right parsing "no tracking" is not always a win.

**Comment by lukedukeus** [comment]
update, i found the file again, and slightly edited it, so now when run, it scrapes the microsoft rewards subreddit for links.
heres the code
################################
import praw
import pandas as pd
import datetime as dt 
import re
import os

reddit = praw.Reddit(client_id='found at https://old.reddit.com/prefs/apps/', 
                     client_secret='found at https://old.reddit.com/prefs/apps/', 
                     user_agent='SCRIPT_NAME', 
                     username='your reddit uname', 
                     password='your reddit pw')
                     
                     
subreddit = reddit.subreddit('MicrosoftRewards')
new = subreddit.new(limit=1000)

dict =        { "body":[]}
f= open("temp.txt","w+")
for submission in new:
    with open("temp.txt", "a", encoding="utf-8") as f:
        f.write(submission.selftext)

 
with open("temp.txt", "r", encoding="utf-8") as f:
        for line in f:
            urls = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', line)
            for url in urls:
                with open("email_links.txt", "a", encoding="utf-8") as f:
                    f.write(url + '\n')
with open("email_links.txt", "r", encoding="utf-8") as f:
    with open("temp.txt", "w", encoding="utf-8") as p:
        for line in f:                  
            line = line.replace("]","\n")
            line = line.replace(")","\n")
            line = line.replace("(","\n")
            p.write(line)
with open("email_links.txt", "w", encoding="utf-8") as f:           
    with open('temp.txt','r', encoding="utf-8") as file:
        for line in file:
            if not line.isspace():
                f.write(line)
                
os.remove("temp.txt")

################################
@xMNG this could easily be turned into a function that you could trigger with something like "--scrape" or so.

**Comment by lukedukeus** [comment]
or, if you prefer to actually be able to read the code:
https://github.com/lukedukeus/scraper/blob/master/scraper.py

**Comment by ShoGinn** [comment]
@lukedukeus awesome scraper.. I personally wouldn't use it only because it seems like MS is really cracking down on the bot's (because of course people abuse it).

And since most of the links can't be verified as tracking or not...

Unless I'm mistaken? Is there a way to tell if links are tracked/untracked?

**Comment by xMNG** [comment]
@lukedukeus very cool code!

@ShoGinn I think most of the email links are standardized formats now, so it's possible to use a regex. But there are enough non-standard links and tracking links floating around that I decided to keep the email link process manual for now (manually load the links into the txt file and have selenium load them, but I will click through any quiz).

**Comment by lukedukeus** [comment]
you could use a dummy account to sign in and check which links are tracking or not, and only use the non tracking ones. ( there are extensions for chrome that can tell which links track or not, so im sure that theres a way to do it) also, ive been using links from r/MicrosoftRewards for about a year and have had no issues.

**Comment by xMNG** [comment]
@lukedukeus Good to know. The way i check for tracking links is to make sure there is no token: no '?=ksjdfk23123' or similar after the url. 

I've learned a lot from coding this project.

**Comment by ShoGinn** [comment]
@lukedukeus which chrome extension ;) I'll decompile it and look at the code

**Comment by lukedukeus** [comment]
@ShoGinn 
"@lukedukeus Good to know. The way i check for tracking links is to make sure there is no token: no '?=ksjdfk23123' or similar after the url.
I've learned a lot from coding this project.

"
i already have the scraper only use links that dont have words like reddit or imgur in them, so you could add another exception for when the link is trackable. it would also be nice if the bot could detect if the link is a quiz, then solve the quiz.

on an unrelated note, do either of you know anthing/ willing to help with some web development python stuff?

**Comment by xMNG** [comment]
@lukedukeus I haven't made the bot auto-complete the email quizzes yet, bc the quizzes are still varied. I will take a long when time permits (could be a long time from now).

I am learning django at the moment. What are you working on?

**Comment by lukedukeus** [comment]
https://www.reddit.com/r/MicrosoftRewards/comments/99tdfl/new_idea_call_for_coders_smart_people/

ive got it almost all done, just need some help with the paypal api and creating a secure login, and finding a place to host it.
