### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by Emeraldop** [xMNG/Microsoft-Rewards-Bot#55]
C:\Users\emrald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

**Comment by ShoGinn** [comment]
This is a requests issue that has already been identified. It does not stop the script 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShoGinn** [comment]
https://github.com/kennethreitz/requests/pull/5063
That is the fix shortly when requests releases new version 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
