### ISSUE TITLE
Log file not being placed in logs folder on *nix systems

### ISSUE THREAD

**Issue by jbfreels** [xMNG/Microsoft-Rewards-Bot#60]
https://github.com/xMNG/Microsoft-Rewards-Bot/blob/dd1891a587dfa0fd6276f521723114b7c1182e24/rewardsbot/logger.py#L32

On my system there is a file being created `logs\ms_rewards.log`, not the file `ms_rewards.log` in a `logs` folder.  

Changing to...
```python
path.join(path.abspath("."), "logs", "ms_rewards.log")
```

resolves the issue on my system.

**Comment by ShoGinn** [comment]
@jbfreels good catch! now sure how that made it by my sensors ;)

**Comment by ShoGinn** [comment]
all fixed and made pretty a8e56a3
