### ISSUE TITLE
Bot is not gaining point

### ISSUE THREAD

**Issue by Mattlau04** [xMNG/Microsoft-Rewards-Bot#61]
when i do "python ms_rewards.py --mobile --pc --quiz", a chrome windows open then imediatly close, and it just output "DevTools listening on ws://127.0.0.1:55319/devtools/browser/3598a25d-0c0a-423c-9e56-0dfa832705ee" but no point are gained
any idea what might cause this?

**Comment by ShoGinn** [comment]
What version of Chrome is installed?
What Operating System?
What Version of Python?

**Comment by Mattlau04** [comment]
Chrome is 74
Os is windows 10
python is 3.6.7

**Comment by Mattlau04** [comment]
oops my bad my default python was 2.7 so i switched to 3.6 and now it works
