### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by j027** [xMNG/Microsoft-Rewards-Bot#64]
Hello,
When I run the bot,  I get this error:
`python ms_rewards.py --headless --mobile --pc --quiz`

`Traceback (most recent call last):
  File "ms_rewards.py", line 833, in <module>
    check_python_version()
  File "ms_rewards.py", line 53, in check_python_version
    if platform.python_version_tuple() < minimum_version:
TypeError: '<' not supported between instances of 'str' and 'int'`

**Comment by ShoGinn** [comment]
the change to the tuple screwed that up.. update incoming in 5 min

**Comment by ShoGinn** [comment]
fixed with  3c68296
