### ISSUE TITLE
Cant "push origin" with github desktop

### ISSUE THREAD

**Issue by MacMarde** [xMNG/Microsoft-Rewards-Bot#66]
Hi am now getting this error while I try to push origin with github desktop:

![grafik](https://user-images.githubusercontent.com/50266741/57940465-d264e580-78cc-11e9-976e-5b00f1d4af03.png)

I did not change any settings in github desktop.

How should I upload my code suggestions?

**Comment by MacMarde** [comment]
Ohh ok I see I need to make a pull request.
I do it tomorrow

**Comment by altsered** [comment]
@MacMarde can you close this issue since it isn't an issue with this repo?
