### ISSUE TITLE
Tried to run on Windows machine

### ISSUE THREAD

**Issue by DimaRazb** [xMNG/Microsoft-Rewards-Bot#72]
Pls don't get me wrong, but I've tried to run this and it fails on log level. 
What I can do with that?

C:\Python\Python37-32>python.exe "C:\Python\master\ms_rewards.py" --headless --mobile --pc --quiz
  File "C:\Python\master\ms_rewards.py", line 61
    if log_level_string not in _LOG_LEVEL_STRINGS:
                                                 ^
IndentationError: unindent does not match any outer indentation level

**Comment by j027** [comment]
It works just fine for me except I’m using python 3.6.

**Comment by DimaRazb** [comment]
You were right, my bad.
Just forgot to install requests module.
