### ISSUE TITLE
Security Info Question

### ISSUE THREAD

**Issue by Brenex** [xMNG/Microsoft-Rewards-Bot#75]
bot hangs at this question

[ms_rewards.log](https://github.com/xMNG/Microsoft-Rewards-Bot/files/3227996/ms_rewards.log)

![20190528%H3544_sb_form_q](https://user-images.githubusercontent.com/3178983/58483857-ffb45d80-812e-11e9-9362-145796fa905c.png)

**Comment by h4x0rm1k3** [comment]
Just visit the site manually and click looks good, that should allow the bot to carry on with it's tasks. If it doesn't and has another similar question then just visit manually again until the bot runs as it should do.

**Comment by ZHAxMDI0** [comment]
I'm adding support for these messages to my fork, but I haven't seen this message before. Can you post the HTML attributes for the buttons?

**Comment by AnthonyBe** [comment]
I had a bunch of these as well. I seem to remember that there was a follow up message window with something else I had to click past?

**Comment by Brenex** [comment]
I clicked through it so I don't have the page attributes anymore. Maybe someone else can nab it?
