### ISSUE TITLE
Im not sure what to do here

### ISSUE THREAD

**Issue by allen453** [xMNG/Microsoft-Rewards-Bot#76]
L

**Comment by allen453** [comment]
well i just downloaded python 3.6 with the right version of request and selenium and still says the same thing

**Comment by h4x0rm1k3** [comment]
I get the same on occasion and it still runs and completes fine so as long as it's completing everything it should do for you then I wouldn't worry about it!

**Comment by allen453** [comment]
so i just let it sit there and it will complete all the task for each account?

**Comment by h4x0rm1k3** [comment]
Should do, let it work for about 15-20 mins and check the log or the microsoft account to see if your points are being logged etc.
