### ISSUE TITLE
Login Loop - Won't Log In

### ISSUE THREAD

**Issue by HQModz** [xMNG/Microsoft-Rewards-Bot#81]
When I start the bot, it types in the email but won't enter the password and refreshes a few times then starts searching without being logged in. I'm certain the json file is set up properly. How can I fix this? Thank you!

**Comment by andrewjmetzger** [comment]
I had the same issue, fixed by opening a new  tab in the chrome instance and logging in manually (as the automated tab reloads, Bing will detect the login). 

You will need to remove thew `--headless` option (or edit `runbot.bat`) for this to work.

I am currently working on code to add support for MS Authenticator/password-less login.

**Comment by andrewjmetzger** [comment]
Hi again @HQModz

While manually opening another tab and entering your password should technically be sufficient, a better solution might be to use [**Microsoft Authenticator**](https://www.microsoft.com/en-us/account/authenticator), a free app that lets you sign in without a password, by using a mobile device instead. 

To resolve the endless password attempts by using Microsoft Authenticator, follow these steps:
1. Enable Microsoft Authenticator for each of your accounts (once per account)
1. Use the `--authenticator` argument when running the bot (or add it to `runbot.bat`, if desired)
1. As the bot runs, respond to each Authenticator prompt to approve each sign-in request  
**NOTE:** This disables headless mode -- you need to pay attention to the bot (periodically) to approve the requests. 

I have submitted a pull request (#82, see above) to have Microsoft Authenticator support added to the bot. While we wait for the maintainers to merge the changes,  use [my copy of the repository](https://github.com/andrewjmetzger/Microsoft-Rewards-Bot/) instead (which already supports Microsoft Authenticator) until the request is merged.

Hope this helps! If you have any questions, feel free to leave a comment and I'll do my best to assist. 😃

**Comment by HQModz** [comment]
@andrewjmetzger Much thanks for the replies! I will give the authenticator a try. Hopefully the normal password login can soon be fixed.

**Comment by ibaiC** [comment]
commenting out the lines `browser.refresh()` in the `wait_until_clickable()` function fixed it for me and has not caused any other issues. It appears as though a webdriver exception is being thrown and the browser is being refreshed before it can input the password.

**Comment by andrewjmetzger** [comment]
Thanks for the discovery @ibaiC; I will try that today. 

if it works, I will submit another pull request and ammend #82 accordingly.

**Comment by HQModz** [comment]
@andrewjmetzger @ibaiC Thank you! Please reply here with any updates

**Comment by Jin6** [comment]
> commenting out the lines `browser.refresh()` in the `wait_until_clickable()` function fixed it for me and has not caused any other issues. It appears as though a webdriver exception is being thrown and the browser is being refreshed before it can input the password.

I confirmed it works , notes that there were 2 lines `browser.refresh()`.

**Comment by andrewjmetzger** [comment]
@ibaiC Confirmed. Fixed in #84.

**Comment by ibaiC** [comment]
Great! :)

**Comment by HQModz** [comment]
@andrewjmetzger @ibaiC @Jin6 
Thank you so much

**Comment by andrewjmetzger** [comment]
You're welcome @HQModz. Please test and report back, whether the fix works or not. 

Seems to do the trick for me, but any feedback would be great. Plus, all of my accounts are 2FA enabled, which limits my ability to test.

**Comment by HQModz** [comment]
> You're welcome @HQModz. Please test and report back, whether the fix works or not.
> 
> Seems to do the trick for me, but any feedback would be great. Plus, all of my accounts are 2FA enabled, which limits my ability to test.

Yes it's working for me now. It inputs the email and password and logs in properly (I don't use 2FA). Thanks again!

**Comment by andrewjmetzger** [comment]
Awesome; that's great news! :smiley:

When you get the chance, please be sure to mark this issue as closed (there should be a button near the top of the page).
