### ISSUE TITLE
Unhandled browser dialogs sometimes cause crashes

### ISSUE THREAD

**Issue by andrewjmetzger** [xMNG/Microsoft-Rewards-Bot#87]
When performing searches in any mode (PC, Edge, or Mobile), Bing occasionally requests a geographic location from the browser. Under some configurations, the ungandled browser dialog can trigger an `AllocateAndMapSharedMemory `exception in chrome, which causes the bot to crash.

In such cases, this can be mitigated by blocking geolocation and notification requests at the browser level.

**Comment by andrewjmetzger** [comment]
Update: Seems that requests for notification access trigger the exception as well.

I will revise the enclosed PR to also block notification requests.

**Comment by HQModz** [comment]
Fix confirmed. Thank you!
