### ISSUE TITLE
Cmd prompt closes without completing any searches.

### ISSUE THREAD

**Issue by syuki3** [xMNG/Microsoft-Rewards-Bot#98]
Not very easy to help in debugging as all I get is what I think is a chrome window flash open, immediately close, and the CMD prompt immediately closing after it.  Not really sure when it started as I wasn't paying attention to the script lately...

Just found the log as I type this and I see 
"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)"

Downgrading chrome seems to be fairly difficult for some reason...  Any chance changes can be made to support chrome 76?

**Comment by govatent** [comment]
All I needed to do was visit the https://chromedriver.chromium.org/ site and download the new driver file from https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/ and overwrite the old file.

**Comment by syuki3** [comment]
Cool, thanks for the input. Will give it a try tonight to see if this fixes my problem.

**Comment by syuki3** [comment]
Worked like a charm.  Get lots of weird errors in the cmd prompt but getting the credit.

**Comment by wastingoctober** [comment]
Thanks. If anyone else on Win10 has issues today, some update apparently caused running "python" to open the Windows 10 store. It lost my path location for Python3. So once I manually added C:\Users\<username>\AppData\Local\Programs\Python\Python37 to my path variable in front of the Windows Store location, it fixed things.

**Comment by h4x0rm1k3** [comment]
> All I needed to do was visit the https://chromedriver.chromium.org/ site and download the new driver file from https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/ and overwrite the old file.

All you need to do is delete the chromedriver from the drivers folder, the bot will auto download the latest version which is as you say currently 76.0
