### ISSUE TITLE
Bot Fails to Run

### ISSUE THREAD

**Issue by pyrokidd89** [xMNG/Microsoft-Rewards-Bot#99]
Every time I run the bot I get this error and the bot closes.

DevTools listening on ws://127.0.0.1:62815/devtools/browser/b612370a-6c12-42c7-8653-d6f51818d61a
[15832:8672:0806/205659.395:ERROR:broker_win.cc(55)] Error reading broker pipe: The pipe has been ended. (0x6D)
[15832:8672:0806/205659.395:ERROR:command_buffer_proxy_impl.cc(94)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed

**Comment by wastingoctober** [comment]
Are you also seeing screenshots that say "Too many requests" in the logs folder?

**Comment by pyrokidd89** [comment]
I fixed it by updating chromeDriver

**Comment by Lukebrisk** [comment]
What version of the ChromeDriver di you update to?

**Comment by h4x0rm1k3** [comment]
@Lukebrisk , I just encountered a similar issue where the bot would just close out on me and spotted an error in the log mentioning that the chrome version needed to be between 71 & 75 and that my version was 2.46 in my drivers folder so all I did was delete the chromedriver from that folder, started the bot again and it grabbed the latest version which is now reporting as  v76.0 (bit higher than the between 71-75 it wanted) and now it works as it should do!
